---
title: "Coronavirus in the US (in progress, updates soon to come)"
output: html_document
---
```{r echo=FALSE,message=FALSE,warning=FALSE}
library(knitr)
library(tidyverse)
library(maps)
library(mapproj)
library(patchwork)
library(ggplot2)
library(plotly)
library(reshape2)
source("analysis.r")
```

<!-- Brief Introduction, link to raw data -->
# Introduction

<!-- graph showing: number of cases and number of deaths across the whole US -->
```{r graph1cases, echo=FALSE}
graph1cases
```

```{r graph1deaths, echo=FALSE}
graph1deaths
```

## Summary Statistics
```{r echo=FALSE, message=FALSE}
kable(table1_cases_and_deaths)
```

<!-- table showing total reported cases and deaths so far; total reported cases and deaths as of today; percent change in the past 14 days -->

<!-- map with widgets for
	hot spots  average daily cases per 100,000 people in the past week >>
	total cases
	total deaths
	deaths per capita
-->

<!-- graph showing number of cases, number of deaths, and number hospitalized by State -->

<!-- table showing total reported cases and deaths so far; total reported cases and deaths as of today; percent change in the past 14 days 
County with the highest across all 3 areas
County with the lowest across all 3 areas 
-->